# Server
server.port=8080

# H2 DB config
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console enable
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL (optional)
spring.jpa.show-sql=true